services:
  pg-admin:
    image: dpage/pgadmin4:9.15
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./servers.json:/pgadmin4/servers.json