services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: my-postgres-pass
      POSTGRES_DB: social-db
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready" ]
    volumes:
      - postgres-data:/var/lib/postgresql/docker

  social-svc:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "7987:8080"

volumes:
  postgres-data:
    driver: local