FROM rust:1.97-alpine3.23 AS builder
WORKDIR /app

RUN apk add protoc protobuf-dev

COPY . .

EXPOSE 8080

ARG SQLX_OFFLINE=true
RUN cargo build

FROM scratch

COPY --from=builder /app/target/debug/social .
COPY config config
COPY migrations migrations

CMD ["./social"]