syntax = "proto3";
package likes;

service Likes {
    rpc like_track(LikeRequest) returns (Empty);
    rpc dislike_track(DislikeRequest) returns (Empty);
    rpc get_liked_tracks(GetLikedTracksRequest) returns (LikedTracksResponse);
    rpc get_likes_count(GetLikesCountRequest) returns (LikesCountResponse);
}

message Empty {}

message LikeRequest {
    int64 user_id = 1;
    int64 track_id = 2;
}

message DislikeRequest {
    int64 user_id = 1;
    int64 track_id = 2;
}

message GetLikedTracksRequest {
    int64 user_id = 1;
    int32 page_number = 2;
    int32 page_size = 3;
}

message GetLikesCountRequest {
    int64 track_id = 1;
}

message LikedTracksResponse {
    repeated int64 track_ids = 1;
    int64 total_count = 2;
}

message LikesCountResponse {
    int64 count = 1;
}